###############################################################################
# Comparative Analysis: Prydz Bay Mizer Model vs Savoca et al. (2024)
# 
# Calculates:
#   1. Normalised indices (pre-whaling = 1.0) for direct comparison
#   2. Fishing impact metrics unique to this modelling approach
#   3. Comparison framework with Savoca et al. estimates
#
# Reference: Savoca et al. (2024) Nature Communications
#            https://doi.org/10.1038/s41467-024-51954-x
#
# Author: Generated for Prydz Bay mizer project
# Date: February 2026
###############################################################################

library(dplyr)
library(tidyr)
library(ggplot2)

# Configuration
OUTPUT_DIR <- "whale_consumption_outputs"

###############################################################################
# Savoca et al. (2024) Reference Values
# From Table 1 and text - CCAMLR Subareas 48.1-48.4 estimates
###############################################################################

# Note: Savoca et al. present ranges; we use their point estimates and ranges
savoca_estimates <- list(
  # Pre-whaling estimates (proxy for carrying capacity)
  prewhaling = list(
    abundance = 180000,  # Combined blue, fin, humpback
    krill_consumption_mt = 51,  # Mt/yr (range: 28-90)
    krill_consumption_low = 28,
    krill_consumption_high = 90
  ),
  # Current (early 2020s) estimates
  current = list(
    abundance = NA,  # Not explicitly stated as single value
    krill_consumption_mt = 18,  # Mt/yr (range: 10-31)
    krill_consumption_low = 10,
    krill_consumption_high = 31
  ),
  # Implied relative change
  relative_change_percent = (18 / 51) * 100  # ~35%
)

cat("=============================================================\n")
cat("COMPARATIVE ANALYSIS: PRYDZ BAY vs SAVOCA et al. (2024)\n")
cat("=============================================================\n\n")

cat("Savoca et al. (2024) Reference Values:\n")
cat("--------------------------------------\n")
cat(sprintf("  Pre-whaling krill consumption: %.0f Mt/yr (range: %.0f-%.0f)\n",
            savoca_estimates$prewhaling$krill_consumption_mt,
            savoca_estimates$prewhaling$krill_consumption_low,
            savoca_estimates$prewhaling$krill_consumption_high))
cat(sprintf("  Current krill consumption:     %.0f Mt/yr (range: %.0f-%.0f)\n",
            savoca_estimates$current$krill_consumption_mt,
            savoca_estimates$current$krill_consumption_low,
            savoca_estimates$current$krill_consumption_high))
cat(sprintf("  Implied relative change:       %.1f%% of pre-whaling\n\n",
            savoca_estimates$relative_change_percent))

###############################################################################
# Load Prydz Bay period summaries
###############################################################################

cat("Loading Prydz Bay mizer model outputs...\n")

# Load period summaries (generated by analyze_baleen_consumption.R)
fishing_ltl <- read.csv(file.path(OUTPUT_DIR, "baleen_ltl_fishing_period_summary.csv"))
climate_ltl <- read.csv(file.path(OUTPUT_DIR, "baleen_ltl_climate_only_period_summary.csv"))
fishing_krill <- read.csv(file.path(OUTPUT_DIR, "baleen_krill_fishing_period_summary.csv"))
climate_krill <- read.csv(file.path(OUTPUT_DIR, "baleen_krill_climate_only_period_summary.csv"))

# Load relative changes
relative_changes <- read.csv(file.path(OUTPUT_DIR, "baleen_relative_changes_modern_vs_prewhaling.csv"))

# Load fishing impact
fishing_impact <- read.csv(file.path(OUTPUT_DIR, "baleen_fishing_impact_all_periods.csv"))

###############################################################################
# 1. NORMALISED INDICES (Pre-whaling = 1.0)
###############################################################################

cat("\n=============================================================\n")
cat("1. NORMALISED CONSUMPTION INDICES (Pre-whaling = 1.0)\n")
cat("=============================================================\n\n")

# Function to calculate normalised indices
calculate_normalised_index <- function(summary_df, baseline_period = "Pre-whaling") {
  baseline_median <- summary_df %>%
    filter(period == baseline_period) %>%
    pull(median_mean)
  
  baseline_mean <- summary_df %>%
    filter(period == baseline_period) %>%
    pull(mean_mean)
  
  summary_df %>%
    mutate(
      index_median = median_mean / baseline_median,
      index_mean = mean_mean / baseline_mean
    ) %>%
    select(period, start_year, end_year, 
           median_mean, index_median, 
           mean_mean, index_mean)
}

# Calculate normalised indices for all scenarios
fishing_ltl_index <- calculate_normalised_index(fishing_ltl) %>%
  mutate(scenario = "Fishing", metric = "LTL")
climate_ltl_index <- calculate_normalised_index(climate_ltl) %>%
  mutate(scenario = "Climate-only", metric = "LTL")
fishing_krill_index <- calculate_normalised_index(fishing_krill) %>%
  mutate(scenario = "Fishing", metric = "Krill")
climate_krill_index <- calculate_normalised_index(climate_krill) %>%
  mutate(scenario = "Climate-only", metric = "Krill")

# Combine all indices
all_indices <- bind_rows(
  fishing_ltl_index,
  climate_ltl_index,
  fishing_krill_index,
  climate_krill_index
)

cat("LTL CONSUMPTION - Normalised Indices:\n")
cat("--------------------------------------\n")
cat("\nFishing scenario:\n")
print(fishing_ltl_index %>% 
        select(period, index_median, index_mean) %>%
        mutate(across(c(index_median, index_mean), ~round(.x, 3))))

cat("\nClimate-only scenario:\n")
print(climate_ltl_index %>% 
        select(period, index_median, index_mean) %>%
        mutate(across(c(index_median, index_mean), ~round(.x, 3))))

cat("\n\nKRILL CONSUMPTION - Normalised Indices:\n")
cat("---------------------------------------\n")
cat("\nFishing scenario:\n")
print(fishing_krill_index %>% 
        select(period, index_median, index_mean) %>%
        mutate(across(c(index_median, index_mean), ~round(.x, 3))))

cat("\nClimate-only scenario:\n")
print(climate_krill_index %>% 
        select(period, index_median, index_mean) %>%
        mutate(across(c(index_median, index_mean), ~round(.x, 3))))

###############################################################################
# 2. COMPARISON WITH SAVOCA et al. RELATIVE DECLINE
###############################################################################

cat("\n=============================================================\n")
cat("2. COMPARISON WITH SAVOCA et al. RELATIVE DECLINE\n")
cat("=============================================================\n\n")

# Extract modern indices for comparison
modern_indices <- all_indices %>%
  filter(period == "Modern") %>%
  select(scenario, metric, index_median, index_mean) %>%
  mutate(
    percent_of_prewhaling_median = index_median * 100,
    percent_of_prewhaling_mean = index_mean * 100
  )

# Savoca comparison
savoca_percent <- savoca_estimates$relative_change_percent

cat("Modern as % of Pre-whaling Consumption:\n")
cat("---------------------------------------\n\n")

cat("Prydz Bay Mizer Model:\n")
for (i in 1:nrow(modern_indices)) {
  row <- modern_indices[i, ]
  cat(sprintf("  %s (%s): %.1f%% (median), %.1f%% (mean)\n",
              row$metric, row$scenario,
              row$percent_of_prewhaling_median,
              row$percent_of_prewhaling_mean))
}

cat(sprintf("\nSavoca et al. (2024) implied estimate: %.1f%%\n", savoca_percent))

# Calculate concordance (how close are the relative changes?)
concordance <- modern_indices %>%
  mutate(
    diff_from_savoca_median = percent_of_prewhaling_median - savoca_percent,
    diff_from_savoca_mean = percent_of_prewhaling_mean - savoca_percent
  )

cat("\nDifference from Savoca et al. estimate:\n")
print(concordance %>% 
        select(scenario, metric, diff_from_savoca_median, diff_from_savoca_mean) %>%
        mutate(across(c(diff_from_savoca_median, diff_from_savoca_mean), ~round(.x, 1))))

###############################################################################
# 3. FISHING IMPACT - UNIQUE CONTRIBUTION OF THIS MODEL
###############################################################################

cat("\n=============================================================\n")
cat("3. FISHING IMPACT: Novel Counterfactual Analysis\n")
cat("=============================================================\n\n")

cat("This analysis provides what Savoca et al. cannot: a counterfactual\n")
cat("comparison between scenarios with and without fishing pressure.\n\n")

# Extract key fishing impact metrics
modern_impact <- fishing_impact %>%
  filter(period == "Modern")

cat("Modern Period Fishing Impact:\n")
cat("-----------------------------\n")
for (i in 1:nrow(modern_impact)) {
  row <- modern_impact[i, ]
  cat(sprintf("\n%s Consumption:\n", row$metric))
  cat(sprintf("  With fishing:      %.0f tonnes/yr\n", row$fishing_median))
  cat(sprintf("  Without fishing:   %.0f tonnes/yr\n", row$climate_median))
  cat(sprintf("  Fishing ratio:     %.1f%% of unfished\n", row$median_ratio))
  cat(sprintf("  Fishing deficit:   %.0f tonnes/yr\n", abs(row$median_diff)))
}

# Calculate fishing impact across all periods
cat("\n\nFishing Impact Trajectory (Fishing as % of Climate-only):\n")
cat("---------------------------------------------------------\n")

fishing_trajectory <- fishing_impact %>%
  select(period, metric, median_ratio) %>%
  pivot_wider(names_from = metric, values_from = median_ratio)

print(fishing_trajectory %>% 
        mutate(across(c(LTL, Krill), ~round(.x, 1))))

###############################################################################
# 4. DIET COMPOSITION STABILITY
###############################################################################

cat("\n=============================================================\n")
cat("4. DIET COMPOSITION: Krill as % of Total LTL Consumption\n")
cat("=============================================================\n\n")

# Calculate krill proportion of LTL for each period and scenario
diet_composition <- fishing_krill %>%
  select(period, krill_median = median_mean, krill_mean = mean_mean) %>%
  left_join(
    fishing_ltl %>% select(period, ltl_median = median_mean, ltl_mean = mean_mean),
    by = "period"
  ) %>%
  mutate(
    krill_proportion_median = (krill_median / ltl_median) * 100,
    krill_proportion_mean = (krill_mean / ltl_mean) * 100,
    scenario = "Fishing"
  )

diet_composition_climate <- climate_krill %>%
  select(period, krill_median = median_mean, krill_mean = mean_mean) %>%
  left_join(
    climate_ltl %>% select(period, ltl_median = median_mean, ltl_mean = mean_mean),
    by = "period"
  ) %>%
  mutate(
    krill_proportion_median = (krill_median / ltl_median) * 100,
    krill_proportion_mean = (krill_mean / ltl_mean) * 100,
    scenario = "Climate-only"
  )

cat("Fishing Scenario:\n")
print(diet_composition %>% 
        select(period, krill_proportion_median, krill_proportion_mean) %>%
        mutate(across(c(krill_proportion_median, krill_proportion_mean), ~round(.x, 1))))

cat("\nClimate-only Scenario:\n")
print(diet_composition_climate %>% 
        select(period, krill_proportion_median, krill_proportion_mean) %>%
        mutate(across(c(krill_proportion_median, krill_proportion_mean), ~round(.x, 1))))

# Assess stability
krill_prop_range_fishing <- range(diet_composition$krill_proportion_median)
krill_prop_range_climate <- range(diet_composition_climate$krill_proportion_median)

cat(sprintf("\nKrill proportion range (Fishing):     %.1f%% - %.1f%%\n",
            krill_prop_range_fishing[1], krill_prop_range_fishing[2]))
cat(sprintf("Krill proportion range (Climate-only): %.1f%% - %.1f%%\n",
            krill_prop_range_climate[1], krill_prop_range_climate[2]))

###############################################################################
# 5. SUMMARY COMPARISON TABLE
###############################################################################

cat("\n=============================================================\n")
cat("5. SUMMARY COMPARISON TABLE\n")
cat("=============================================================\n\n")

# Create summary comparison
summary_comparison <- data.frame(
  Metric = c(
    "Modern/Pre-whaling (Savoca et al.)",
    "Modern/Pre-whaling (Mizer - Krill, Fishing, Median)",
    "Modern/Pre-whaling (Mizer - Krill, Fishing, Mean)",
    "Modern/Pre-whaling (Mizer - LTL, Fishing, Median)",
    "Modern/Pre-whaling (Mizer - LTL, Fishing, Mean)",
    "Fishing/Unfished (Mizer - Modern, Krill)",
    "Fishing/Unfished (Mizer - Modern, LTL)"
  ),
  Value_Percent = c(
    savoca_percent,
    modern_indices %>% filter(metric == "Krill", scenario == "Fishing") %>% pull(percent_of_prewhaling_median),
    modern_indices %>% filter(metric == "Krill", scenario == "Fishing") %>% pull(percent_of_prewhaling_mean),
    modern_indices %>% filter(metric == "LTL", scenario == "Fishing") %>% pull(percent_of_prewhaling_median),
    modern_indices %>% filter(metric == "LTL", scenario == "Fishing") %>% pull(percent_of_prewhaling_mean),
    modern_impact %>% filter(metric == "Krill") %>% pull(median_ratio),
    modern_impact %>% filter(metric == "LTL") %>% pull(median_ratio)
  ),
  Source = c(
    "Savoca et al. 2024",
    rep("Prydz Bay Mizer", 6)
  )
)

print(summary_comparison %>% mutate(Value_Percent = round(Value_Percent, 1)))

###############################################################################
# 6. SAVE OUTPUTS
###############################################################################

cat("\n=============================================================\n")
cat("SAVING COMPARATIVE ANALYSIS OUTPUTS\n")
cat("=============================================================\n\n")

# Save normalised indices
write.csv(all_indices, 
          file.path(OUTPUT_DIR, "normalised_consumption_indices.csv"),
          row.names = FALSE)

# Save comparison summary
write.csv(summary_comparison,
          file.path(OUTPUT_DIR, "savoca_comparison_summary.csv"),
          row.names = FALSE)

# Save diet composition
diet_all <- bind_rows(diet_composition, diet_composition_climate)
write.csv(diet_all,
          file.path(OUTPUT_DIR, "diet_composition_krill_proportion.csv"),
          row.names = FALSE)

cat("Saved:\n")
cat("  - normalised_consumption_indices.csv\n")
cat("  - savoca_comparison_summary.csv\n")
cat("  - diet_composition_krill_proportion.csv\n")

###############################################################################
# 7. VISUALISATION: Normalised Index Trajectory
###############################################################################

cat("\n=============================================================\n")
cat("CREATING VISUALISATION\n")
cat("=============================================================\n\n")

# Create mid-point years for plotting
period_midpoints <- data.frame(
  period = c("Pre-whaling", "Early whaling", "Peak whaling", 
             "Post-whaling", "Krill fishing", "Modern"),
  mid_year = c(1860, 1910, 1947, 1973, 1986, 2005)
)

# Prepare data for plotting
plot_data <- all_indices %>%
  left_join(period_midpoints, by = "period") %>%
  mutate(
    scenario_metric = paste(scenario, metric, sep = " - ")
  )

# Add Savoca reference line data
savoca_ref <- data.frame(
  mid_year = c(1860, 2005),
  index = c(1.0, savoca_percent / 100),
  scenario_metric = "Savoca et al. (2024)"
)

# Create plot
p <- ggplot() +
  # Mizer model trajectories
  geom_line(data = plot_data,
            aes(x = mid_year, y = index_median, 
                colour = scenario_metric, linetype = scenario_metric),
            linewidth = 1) +
  geom_point(data = plot_data,
             aes(x = mid_year, y = index_median, 
                 colour = scenario_metric, shape = scenario_metric),
             size = 3) +
  # Savoca reference (implied trajectory)
  geom_line(data = savoca_ref,
            aes(x = mid_year, y = index),
            colour = "black", linetype = "dashed", linewidth = 1.2) +
  geom_point(data = savoca_ref,
             aes(x = mid_year, y = index),
             colour = "black", shape = 4, size = 4, stroke = 1.5) +
  # Reference line at 1.0
  geom_hline(yintercept = 1.0, linetype = "dotted", colour = "grey50") +
  # Formatting
  scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.5, 0.25)) +
  scale_x_continuous(breaks = c(1860, 1910, 1947, 1973, 1986, 2005)) +
  scale_colour_manual(values = c(
    "Fishing - Krill" = "#E64B35",
    "Fishing - LTL" = "#4DBBD5",
    "Climate-only - Krill" = "#F39B7F",
    "Climate-only - LTL" = "#91D1C2"
  )) +
  scale_linetype_manual(values = c(
    "Fishing - Krill" = "solid",
    "Fishing - LTL" = "solid",
    "Climate-only - Krill" = "dashed",
    "Climate-only - LTL" = "dashed"
  )) +
  scale_shape_manual(values = c(
    "Fishing - Krill" = 16,
    "Fishing - LTL" = 17,
    "Climate-only - Krill" = 1,
    "Climate-only - LTL" = 2
  )) +
  labs(
    title = "Baleen Whale Consumption: Prydz Bay Mizer vs Savoca et al. (2024)",
    subtitle = "Normalised to pre-whaling baseline (1841-1880 = 1.0)",
    x = "Year (period midpoint)",
    y = "Normalised consumption index",
    colour = "Scenario",
    linetype = "Scenario",
    shape = "Scenario",
    caption = "Black dashed line with X markers: Savoca et al. (2024) implied trajectory"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    legend.box = "vertical",
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  guides(colour = guide_legend(nrow = 2))

# Save plot
ggsave(file.path(OUTPUT_DIR, "normalised_index_comparison.png"),
       p, width = 10, height = 7, dpi = 300)

ggsave(file.path(OUTPUT_DIR, "normalised_index_comparison.pdf"),
       p, width = 10, height = 7)

cat("Saved visualisations: normalised_index_comparison.png and .pdf\n")

cat("\n=============================================================\n")
cat("COMPARATIVE ANALYSIS COMPLETE\n")
cat("=============================================================\n")
