---
title: "Diet Plots"
output: html_notebook
---

```{r}
library(mizerExperimental)
library(therMizer)
```


Load steady therMizer parameters:
```{r}
# Generate parameters
params <- readRDS("therMizer_params_v04.RDS")
```


```{r}
diet <- getDiet(params, proportion = F)

df_diet <- melt(diet)

df_diet_summary <- df_diet %>% 
  filter(!prey == "Resource") %>% 
  group_by(predator, prey) %>% 
  summarise(diet = sum(value)) %>% 
  group_by(predator) %>% 
  mutate(all_diet = sum(diet),
         prop_diet = diet/all_diet)
  

df_diet_summary
```



```{r}
ggplot(df_diet_summary, aes())
```



```{r}
# Libraries
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/13_AdjacencyDirectedWeighted.csv", header=TRUE)
# Package
library(networkD3)

# I need a long format
data_long <- data %>%
  rownames_to_column %>%
  gather(key = 'key', value = 'value', -rowname) %>%
  filter(value > 0)
colnames(data_long) <- c("source", "target", "value")
data_long$target <- paste(data_long$target, " ", sep="")

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(name=c(as.character(data_long$source), as.character(data_long$target)) %>% unique())
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
data_long$IDsource=match(data_long$source, nodes$name)-1 
data_long$IDtarget=match(data_long$target, nodes$name)-1

# prepare colour scale
ColourScal ='d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'

# Make the Network
sankeyNetwork(Links = data_long, Nodes = nodes,
                     Source = "IDsource", Target = "IDtarget",
                     Value = "value", NodeID = "name", 
                     sinksRight=FALSE, colourScale=ColourScal, nodeWidth=40, fontSize=13, nodePadding=20)
```




```{r}
# Libraries
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)

# # Load dataset from github
# data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/13_AdjacencyDirectedWeighted.csv", header=TRUE)
# # Package
# library(networkD3)
# 
# # I need a long format
# data_long <- data %>%
#   rownames_to_column %>%
#   gather(key = 'key', value = 'value', -rowname) %>%
#   filter(value > 0)
# colnames(data_long) <- c("source", "target", "value")
# data_long$target <- paste(data_long$target, " ", sep="")

# # From these flows we need to create a node data frame: it lists every entities involved in the flow
# nodes <- data.frame(name=c(as.character(data_long$source), as.character(data_long$target)) %>% unique())

nodes <- data.frame(name=c(as.character(df_diet_summary$prey), as.character(df_diet_summary$predator))) %>% unique

nodes <- rbind(nodes,nodes)
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
df_diet_summary$IDprey=match(df_diet_summary$prey, nodes$name)-1 
df_diet_summary$IDpredator=match(df_diet_summary$predator, nodes$name)-1

# prepare colour scale
ColourScal ='d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'

# Make the Network
sankeyNetwork(Links = df_diet_summary, Nodes = nodes,
                     Source = "IDprey", Target = "IDpredator",
                     Value = "prop_diet", NodeID = "name", 
                     sinksRight=FALSE, nodeWidth=40, fontSize=13, nodePadding=20)
```
