---
title: "Emergent PPMR"
output: html_notebook
---

```{r}
library(therMizer)
params <-readRDS("therMizer_params_v04.RDS")


```


```{r}
sim <- project(params, t_max = 100)
```


```{r}
getDietComp <- function (params, n = initialN(params), n_pp = initialNResource(params),

                         n_other = initialNOther(params), proportion = TRUE)

{

  params <- validParams(params)

  pred_kernel(params) <- pred_kernel(params) #required to make this work

  species <- params@species_params$species

  no_sp <- length(species)

  no_w <- length(params@w)

  no_w_full <- length(params@w_full)

  no_other <- length(params@other_encounter)

  other_names <- names(params@other_encounter)

  assertthat::assert_that(identical(dim(n), c(no_sp, no_w)), length(n_pp) ==

                            no_w_full)

 

  n_tot <- sweep(n, 2, params@w * params@dw, "*")

  diet_comp <- array(0, dim = c(dim(n_tot),no_sp + 1, no_w_full),

                     dimnames = list("Predator" = species,

                                     "wPredator" = params@w,

                                     "Prey" = c(as.character(species), "Resource"),#, other_names),

                                     "wPrey" = params@w_full))

 

  idx_sp <- (no_w_full - no_w + 1):no_w_full

  # if (!is.null(comment(params@pred_kernel))) {

    ## code to keep prey size | works only without other backgrounds now

   

    for(iPredator in 1:dim(diet_comp)[1])

    {

      for(wPredator in 1:dim(diet_comp)[2])

      {

        for(iPrey in 1:no_sp)

        {

          for(wPrey in 1:no_w) # assuming that w is the tail of w_full, won't work if w_full gets larger than w

          {

            diet_comp[iPredator,wPredator,iPrey,wPrey] <- params@pred_kernel[iPredator,wPredator, (idx_sp[wPrey])] *

              n_tot[iPrey,wPrey]

           

          }

        }

      }

    }

    diet_comp[,,no_sp+1,] <- sweep(params@pred_kernel,

                                   3, params@dw_full * params@w_full * n_pp, "*")

   

    ###

   

  # }

  # else {

  #   prey <- matrix(0, nrow = no_sp + 1, ncol = no_w_full)

  #   prey[1:no_sp, idx_sp] <- sweep(n, 2, params@w * params@dw,

  #                                  "*")

  #   prey[no_sp + 1, ] <- n_pp * params@w_full * params@dw_full

  #   ft <- array(rep(params@ft_pred_kernel_e, times = no_sp +

  #                     1) * rep(mvfft(t(prey)), each = no_sp), dim = c(no_sp,

  #                                                                     no_w_full, no_sp + 1))

  #   ft <- matrix(aperm(ft, c(2, 1, 3)), nrow = no_w_full)

  #   ae <- array(Re(mvfft(ft, inverse = TRUE)/no_w_full),

  #               dim = c(no_w_full, no_sp, no_sp + 1))

  #   ae <- ae[idx_sp, , , drop = FALSE]

  #   ae <- aperm(ae, c(2, 1, 3))

  #   ae[ae < 1e-18] <- 0

  #   diet_comp[, , 1:(no_sp + 1),] <- ae

  # }

 

  inter <- cbind(params@interaction, params@species_params$interaction_resource)

 

  diet_comp[, , 1:(no_sp + 1),] <- sweep(sweep(diet_comp[, , 1:(no_sp + 1),, drop = FALSE], c(1, 3), inter, "*"), c(1, 2), params@search_vol, "*")

 

  for (i in seq_along(params@other_encounter)) {

    diet_comp[, , no_sp + 1 + i,] <- do.call(params@other_encounter[[i]],

                                             list(params = params, n = n, n_pp = n_pp, n_other = n_other,

                                                  component = names(params@other_encounter)[[i]]))

  }

  f <- getFeedingLevel(params, n, n_pp)

  fish_mask <- n > 0

  diet_comp <- sweep(diet_comp, c(1, 2), (1 - f) * fish_mask, "*")

  if (proportion) {

    total <- rowSums(diet_comp, dims = 2)

    diet_comp <- sweep(diet_comp, c(1, 2), total, "/")

    diet_comp[is.nan(diet_comp)] <- 0

  }

  return(diet_comp)

}

 

getRealisedPPMRs <- function(params) {

  SpIdx <- 1:nrow(params@species_params)

  rPPMR <- vector("numeric", length = length(SpIdx)) # SpIdx is the species index (numeric in my model)

 

  DietComp <- getDietComp(params)

 

  for(iSpecies in SpIdx) {

    speciesDat <- DietComp[iSpecies,,,] # this is diet per predator/predator size/prey/prey size 

    # no need to know prey identity

    speciesDat<- apply(speciesDat,c(1,3),sum)

   

    # for each size class need PPMR value

    speciesPPMR <- NULL

    for(iSize in 1:length(dimnames(speciesDat)$wPred)) {

     

      if(sum(speciesDat[iSize,])) {# if there is something at this size

        sizeDat <- speciesDat[iSize,]

        # for now the easy way

        # PreferredSizeClass <- which(sizeDat == max(sizeDat))  # in my model all diet profiles are bell curves on the prey size      

        PreferredSizeClass <- weighted.mean(params@w_full,sizeDat, na.rm = TRUE)

        sizePPMR <- as.numeric(dimnames(speciesDat)$wPred[iSize])/PreferredSizeClass

        speciesPPMR <- c(speciesPPMR,sizePPMR)

      }

    }

    rPPMR[iSpecies] <- weighted.mean(speciesPPMR,params@initial_n[iSpecies,which(params@initial_n[iSpecies,]>0)],na.rm = T)

  }

  names(rPPMR) <- params@species_params$species

  return(rPPMR)

}

 

getRealisedPPMRs(NS_params)

getRealisedPPMRs(params)
```



```{r}
# data for dashed line where expected prey size is 10% of predator size
  df_ref <- tibble(
    Predator_Size = c(min(df_diet$wPredator), max(df_diet$wPredator))
  )
  # df_ref$Expected_Prey_Size_PPMR100000 = 0.00001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR10000 = 0.0001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR1000 = 0.001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR100 = 0.01*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR10 = 0.1*df_ref$Predator_Size
  df_ref$mesozooplankton               = 8.001325e+01*df_ref$Predator_Size
  df_ref$baleen_whales = 1.783887e+07*df_ref$Predator_Size
  df_ref$Expected_Prey_Size_PPMR1000 = 0.001*df_ref$Predator_Size
  df_ref$Expected_Prey_Size_PPMR100 = 0.01*df_ref$Predator_Size
  df_ref$Expected_Prey_Size_PPMR10 = 0.1*df_ref$Predator_Size


  ggplot() +
    geom_line(data = df_ref, aes(x = Predator_Size, y = mesozooplankton),
              linetype = "solid") +
    geom_line(data = df_ref, aes(x = Predator_Size, y = baleen_whales),
              linetype = "solid", colour = "red") +
    # geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR1000),
    #           linetype = "longdash") +
    # geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR10000),
    #           linetype = "dashed") +
    # geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR100000),
    #           linetype = "dotted") +
    # geom_line(data = df_plot_comb,
    #           aes(x = Predator_Size, y = mean_prey_size, color = Predator), size = 1) +
    scale_x_log10() +
    scale_y_log10() +
    # facet_wrap( ~ Predator) +
    labs(x = "Predator size", y = "Mean prey size") +
    theme_bw()
```




```{r}
# works only if predation kernel is supplied at the moment. If it's not run this first:
pred_kernel(params) <- pred_kernel(params)
getDietComp <- function (params, n = initialN(params), n_pp = initialNResource(params),
                      n_other = initialNOther(params), proportion = TRUE)
{
  params <- validParams(params)
  species <- params@species_params$species
  no_sp <- length(species)
  no_w <- length(params@w)
  no_w_full <- length(params@w_full)
  no_other <- length(params@other_encounter)
  other_names <- names(params@other_encounter)
  assertthat::assert_that(identical(dim(n), c(no_sp, no_w)), length(n_pp) ==
                no_w_full)

  idx_sp <- (no_w_full - no_w + 1):no_w_full
  if (!is.null(comment(params@pred_kernel))) {
    ## code to keep prey size | works only without other backgrounds now
    n_tot <- sweep(n, 2, params@w * params@dw, "*")
    diet_comp <- array(0, dim = c(dim(n_tot),no_sp + 1, no_w_full),
                       dimnames = list("Predator" = species,
                                       "wPredator" = params@w,
                                       "Prey" = c(as.character(species), "Resource"),#, other_names),
                                       "wPrey" = params@w_full))
    for(iPredator in 1:dim(diet_comp)[1])
    {
      for(wPredator in 1:dim(diet_comp)[2])
      {
        for(iPrey in 1:no_sp)
        {
          for(wPrey in 1:no_w) # assuming that w is the tail of w_full, won't work if w_full gets larger than w
          {
            diet_comp[iPredator,wPredator,iPrey,wPrey] <- params@pred_kernel[iPredator,wPredator, (idx_sp[wPrey])] *
              n_tot[iPrey,wPrey]
            
          }
        }
      }
    }
    diet_comp[,,no_sp+1,] <- sweep(params@pred_kernel,
                                   3, params@dw_full * params@w_full * n_pp, "*")
    
    ###

  }
  else {
    prey <- matrix(0, nrow = no_sp + 1, ncol = no_w_full)
    prey[1:no_sp, idx_sp] <- sweep(n, 2, params@w * params@dw,
                                   "*")
    prey[no_sp + 1, ] <- n_pp * params@w_full * params@dw_full
    ft <- array(rep(params@ft_pred_kernel_e, times = no_sp +
                      1) * rep(mvfft(t(prey)), each = no_sp), dim = c(no_sp,
                                                                      no_w_full, no_sp + 1))
    ft <- matrix(aperm(ft, c(2, 1, 3)), nrow = no_w_full)
    ae <- array(Re(mvfft(ft, inverse = TRUE)/no_w_full),
                dim = c(no_w_full, no_sp, no_sp + 1))
    ae <- ae[idx_sp, , , drop = FALSE]
    ae <- aperm(ae, c(2, 1, 3))
    ae[ae < 1e-18] <- 0
    diet[, , 1:(no_sp + 1)] <- ae
  }
  
  inter <- cbind(params@interaction, params@species_params$interaction_resource)

  diet_comp[, , 1:(no_sp + 1),] <- sweep(sweep(diet_comp[, , 1:(no_sp + 1),, drop = FALSE], c(1, 3), inter, "*"), c(1, 2), params@search_vol, "*")
  
  for (i in seq_along(params@other_encounter)) {
    diet[, , no_sp + 1 + i] <- do.call(params@other_encounter[[i]],
                                       list(params = params, n = n, n_pp = n_pp, n_other = n_other,
                                            component = names(params@other_encounter)[[i]]))
  }
  f <- getFeedingLevel(params, n, n_pp)
  fish_mask <- n > 0
  diet_comp <- sweep(diet_comp, c(1, 2), (1 - f) * fish_mask, "*")
  if (proportion) {
    total <- rowSums(diet_comp, dims = 2)
    diet_comp <- sweep(diet_comp, c(1, 2), total, "/")
    diet_comp[is.nan(diet_comp)] <- 0
  }
  return(diet_comp)
}



```


```{r}
diet <- getDietComp(params)
```



```{r}
dim(diet)
head(diet)
```
Predator, Pred size, Prey, Prey size


```{r}
library(tidyverse)
df_diet <- melt(diet)
glimpse(df_diet)
head(df_diet)
summary(df_diet)
```


```{r}

df_n <- sim@n[100,,]

N <- melt(df_n)

head(N)

names(N) # [1] "sp"    "w"     "value"

names(N) <- c("Predator","wPredator","N")

# df_n$wPredator <- as.factor(df_n$wPredator)
# df_diet$wPredator <- as.factor(df_diet$wPredator)
```

```{r}
 ## Combine abundance df with diet df

df_ind_PPMR_prelim <- df_diet %>%
    left_join(N, by = c("Predator", "wPredator"))
  
head(df_ind_PPMR_prelim)
```



```{r}
df_final <- df_ind_PPMR_plot %>%
    mutate(per_capita_diet_N = ((Prey_Abundance/Predator_Abundance)/Prey_Size))
  
  df_final_clean <- df_final[Reduce(`&`, lapply(df_final, function(x) !is.na(x)  & is.finite(x))),]
```


```{r}
Emergent_PPMR_Allometry <- function(model){
 
  # model <- Model
  # Average diet array for each predator size class for the final half of the projection
  dynamdiet = apply(model$dynam_diet_full[c(floor(0.5*dim(model$dynam_diet_full)[1]):dim(model$dynam_diet_full)[1]),,,,], c(2,3,4,5), mean)
  phytodiet = apply(model$phyto_diet_full[c(floor(0.5*dim(model$phyto_diet_full)[1]):dim(model$phyto_diet_full)[1]),,,], c(2,3,4), mean)
  
  tmax <- model$param$tmax
  tmax <- tmax-1
  time_cutoff <- tmax/2
  w <- model$w
  
  ## Extract abundance matrix, average over last 50% of save time steps
  df_N <- model$N
  N_ave <- apply(df_N[time_cutoff:tmax,,], c(2,3), FUN = mean, na.rm = TRUE)
  
  N_df <- melt(N_ave)
  
  names(N_df) <- c("Predator_Species", "Predator_Size_Class", "Predator_Abundance")
  
  N_df$Predator_Species <- as.factor(N_df$Predator_Species)
  
  
  curr_phyto_diet <- phytodiet # Current phyto diet
  curr_dynam_diet <- dynamdiet # Current heterotroph diet
  
  start_dynam_tl <- matrix(2, nrow = dim(dynamdiet)[1], ncol = dim(dynamdiet)[2]) # Start TL for dynamic size groups - start at 2 for all groups and sizes
  
  total_diet <- apply(curr_phyto_diet, c(1,2), sum) + apply(curr_dynam_diet, c(1,2), sum) # Total consumption, in grams wet weight, by pred group and pred size
  
  curr_phyto_frac <- apply(sweep(curr_phyto_diet, c(1,2), total_diet, '/'), c(1,2), sum) # Fraction of diet from phyto, by pred group and pred sizes
  curr_dynam_frac <- sweep(curr_dynam_diet, c(1,2), total_diet, '/') # Fraction of diet from each prey group and prey size, for each pred group and pred size
  
  curr_dynam_frac_melt <- melt(curr_dynam_frac)
  curr_phyto_frac_melt <- melt(curr_phyto_frac)
  
  # Assign names to all variables in df_diet
  names(curr_phyto_frac_melt) <- c("Predator_Species", "Predator_Size_Class", "Prey_Frac")
  
  # make predators and prey factor variables
  curr_phyto_frac_melt$Predator_Species <- as.factor(curr_phyto_frac_melt$Predator_Species)
  
  df_size_classes <- model$w # Create new object with list of size classes in log10 g
  df_size_classes <- as.data.frame(df_size_classes) # Convert to a dataframe
  names(df_size_classes) <- c("Predator_Size") # Create new name Size for the variable
  df_size_classes$Predator_Size_Class <- 1:length(model$w)
  
  df_species_predator <- model$param$groups$species # Create new object with species names from model
  df_species_predator <- as.data.frame((df_species_predator)) # Convert to a dataframe
  names(df_species_predator) <- c("Predator") # Rename variable
  df_species_predator$Predator_Species <- 1:length(model$param$groups$species) # Create new integer variable in ascending order with 'Species'
  df_species_predator$Predator_Species <- as.factor(df_species_predator$Predator_Species) # Convert to factor
  
  # df_phyto_size_classes <- model$w_phyto # Create new object with list of size classes in log10 g
  # df_phyto_size_classes <- as.data.frame(df_phyto_size_classes) # Convert to a dataframe
  # names(df_phyto_size_classes) <- c("Prey_Size") # Create new name Size for the variable
  # df_phyto_size_classes$Prey_Size_Class <- 1:length(model$w_phyto)
  # 
  ## join df_N with df_size_class data in order to create log10 size classes rather then the size     class integer 1:184 that is in df_N
  df_combined_frac <- left_join(curr_phyto_frac_melt, df_size_classes,
                                by="Predator_Size_Class") %>%
    
    left_join(df_species_predator,
              by="Predator_Species") # %>%
  # left_join(df_phyto_size_classes,
  #           by="Prey_Size_Class")
  
  df_combined_frac$Prey <- c("Phyto")
  
  ### Dynamic diet dataframe
  
  
  # names(dynamdiet)
  
  # Assign names to all variables in df_diet
  names(curr_dynam_frac_melt) <- c("Predator_Species", "Predator_Size_Class", "Prey_Species", "Prey_Size_Class", "Prey_Frac")
  
  # make predators and prey factor variables
  curr_dynam_frac_melt$Predator_Species <- as.factor(curr_dynam_frac_melt$Predator_Species)
  curr_dynam_frac_melt$Prey_Species <- as.factor(curr_dynam_frac_melt$Prey_Species)
  
  # df_size_classes <- model$w # Create new object with list of size classes in log10 g
  # df_size_classes <- as.data.frame(df_size_classes) # Convert to a dataframe
  # names(df_size_classes) <- c("Predator_Size") # Create new name Size for the variable
  # df_size_classes$Predator_Size_Class <- 1:length(model$w)
  
  df_species_prey <- model$param$groups$species # Create new object with species names from model
  df_species_prey <- as.data.frame((df_species_prey)) # Convert to a dataframe
  names(df_species_prey) <- c("Prey") # Rename variable
  df_species_prey$Prey_Species <- 1:length(model$param$groups$species) # Create new integer variable in ascending order with 'Species'
  df_species_prey$Prey_Species <- as.factor(df_species_prey$Prey_Species) # Convert to factor
  
  df_prey_size_classes <- model$w # Create new object with list of size classes in log10 g
  df_prey_size_classes <- as.data.frame(df_prey_size_classes) # Convert to a dataframe
  names(df_prey_size_classes) <- c("Prey_Size") # Create new name Size for the variable
  df_prey_size_classes$Prey_Size_Class <- 1:length(model$w)
  
  ## join df_N with df_size_class data in order to create log10 size classes rather then the size     class integer 1:184 that is in df_N
  df_combined_dynam_frac <- left_join(curr_dynam_frac_melt, df_size_classes,
                                      by="Predator_Size_Class") %>%
    
    left_join(df_species_predator,
              by="Predator_Species") %>%
    left_join(df_prey_size_classes,
              by="Prey_Size_Class") %>%
    left_join(df_species_prey,
              by="Prey_Species")
  
  df_comb_all <- df_combined_dynam_frac %>%
    group_by(Predator,Predator_Size, Prey) %>%
    summarise(Prey_Frac = sum(Prey_Frac)) 
  
  
  df_phyto_frac_v1 <- df_combined_frac %>%
    select(Predator, Prey, Predator_Size, Prey_Frac)
  
  df_test_v3 <- bind_rows(df_comb_all,df_phyto_frac_v1)
  
  df_test_v3$Prey <- as.factor(df_test_v3$Prey)
  
  df_test_v3 <- df_test_v3[Reduce(`&`, lapply(df_test_v3, function(x) !is.na(x)  & is.finite(x))),]
  
  df_cephs_prey_frac <- df_test_v3 %>%
    filter(Prey == "Active Cephs"|Prey == "Inactive Cephs") %>%
    group_by(Predator, Predator_Size) %>%
    summarise(Prey_Frac = sum(Prey_Frac))
  
  df_cephs_prey_frac$Prey <- "Cephs"
  
  df_rest_prey <- df_test_v3 %>%
    filter(Prey == "Fish"|Prey == "Zooplankton"|Prey == "Phyto")
  
  df_ceph_prey_comb <- rbind(df_cephs_prey_frac, df_rest_prey)
  
  df_ceph_prey_comb$Prey <- as.factor(df_ceph_prey_comb$Prey)
  
  
  #####
  
  df_d_frac <- df_comb_all %>%
    select(Predator, Prey, Predator_Size, Prey_Frac)
  df_pd_frac <- df_combined_frac %>%
    select(Predator, Prey, Predator_Size, Prey_Frac)
  
  df_d_frac <- df_d_frac[Reduce(`&`, lapply(df_d_frac, function(x) !is.na(x)  & is.finite(x))),]
  
  df_pd_frac <- df_pd_frac[complete.cases(df_pd_frac),]
  
  df_frac <- bind_rows(df_d_frac, df_pd_frac) # join data frames, one on top of the other
  
  # ggplot(df_frac, aes(x=log10(Predator_Size), y = Prey_Frac, fill = Prey)) +
  #   geom_area() +
  #   facet_wrap(~Predator, scales = "free_x") +
  #   scale_fill_manual(name = 'Prey',
  #                     values =c("#F8766D","#7CAE00", "#00BFC4","green2","#C77CFF"),
  #                     labels = c('Active', 'Fish','Inactive', "Phytoplankton",'Zooplankton')) +
  #   theme_classic() +
  #   xlab(expression(paste("Predator ",Size~(10^X~g)))) +
  #   ylab("Prey Proportion")
  

  
  phytodiet <- melt(phytodiet)
  # names(phytodiet)
  
  # Assign names to all variables in df_diet
  names(phytodiet) <- c("Predator_Species", "Predator_Size_Class", "Prey_Size_Class", "Prey_Abundance")
  
  # make predators and prey factor variables
  phytodiet$Predator_Species <- as.factor(phytodiet$Predator_Species)
  
  df_size_classes <- model$w # Create new object with list of size classes in log10 g
  df_size_classes <- as.data.frame(df_size_classes) # Convert to a dataframe
  names(df_size_classes) <- c("Predator_Size") # Create new name Size for the variable
  df_size_classes$Predator_Size_Class <- 1:length(model$w)
  
  df_species_predator <- model$param$groups$species # Create new object with species names from model
  df_species_predator <- as.data.frame((df_species_predator)) # Convert to a dataframe
  names(df_species_predator) <- c("Predator") # Rename variable
  df_species_predator$Predator_Species <- 1:length(model$param$groups$species) # Create new integer variable in ascending order with 'Species'
  df_species_predator$Predator_Species <- as.factor(df_species_predator$Predator_Species) # Convert to factor
  
  df_phyto_size_classes <- model$w_phyto # Create new object with list of size classes in log10 g
  df_phyto_size_classes <- as.data.frame(df_phyto_size_classes) # Convert to a dataframe
  names(df_phyto_size_classes) <- c("Prey_Size") # Create new name Size for the variable
  df_phyto_size_classes$Prey_Size_Class <- 1:length(model$w_phyto)
  
  ## join df_N with df_size_class data in order to create log10 size classes rather then the size     class integer 1:184 that is in df_N
  df_combined <- left_join(phytodiet, df_size_classes,
                           by="Predator_Size_Class") %>%
    
    left_join(df_species_predator,
              by="Predator_Species") %>%
    left_join(df_phyto_size_classes,
              by="Prey_Size_Class")
  
  df_combined <- df_combined %>%
    mutate(Prey_Biomass = Prey_Abundance*Prey_Size)
  
  df_combined$Prey <- c("Phyto")
  
  ### Dynamic diet dataframe
  
  dynamdiet <- melt(dynamdiet)
  
  # names(dynamdiet)
  
  # Assign names to all variables in df_diet
  names(dynamdiet) <- c("Predator_Species", "Predator_Size_Class", "Prey_Species", "Prey_Size_Class", "Prey_Abundance")
  
  # make predators and prey factor variables
  dynamdiet$Predator_Species <- as.factor(dynamdiet$Predator_Species)
  dynamdiet$Prey_Species <- as.factor(dynamdiet$Prey_Species)
  
  # df_size_classes <- model$w # Create new object with list of size classes in log10 g
  # df_size_classes <- as.data.frame(df_size_classes) # Convert to a dataframe
  # names(df_size_classes) <- c("Predator_Size") # Create new name Size for the variable
  # df_size_classes$Predator_Size_Class <- 1:length(model$w)
  
  df_species_prey <- model$param$groups$species # Create new object with species names from model
  df_species_prey <- as.data.frame((df_species_prey)) # Convert to a dataframe
  names(df_species_prey) <- c("Prey") # Rename variable
  df_species_prey$Prey_Species <- 1:length(model$param$groups$species) # Create new integer variable in ascending order with 'Species'
  df_species_prey$Prey_Species <- as.factor(df_species_prey$Prey_Species) # Convert to factor
  
  df_prey_size_classes <- model$w # Create new object with list of size classes in log10 g
  df_prey_size_classes <- as.data.frame(df_prey_size_classes) # Convert to a dataframe
  names(df_prey_size_classes) <- c("Prey_Size") # Create new name Size for the variable
  df_prey_size_classes$Prey_Size_Class <- 1:length(model$w)
  
  ## join df_N with df_size_class data in order to create log10 size classes rather then the size     class integer 1:184 that is in df_N
  df_combined_dynam <- left_join(dynamdiet, df_size_classes,
                           by="Predator_Size_Class") %>%
    
    left_join(df_species_predator,
              by="Predator_Species") %>%
    left_join(df_prey_size_classes,
              by="Prey_Size_Class") %>%
    left_join(df_species_prey,
              by="Prey_Species")
  
  
  ###
  
  df_d <- df_combined_dynam %>%
    select(Predator, Prey, Predator_Size, Prey_Size, Prey_Abundance)
  df_pd <- df_combined %>%
    select(Predator, Prey, Predator_Size, Prey_Size, Prey_Abundance)
  
  df <- rbind(df_d, df_pd) # join data frames, one on top of the other
  
  ## Combine abundance df with diet df

  df_ind_PPMR_prelim <- N_df %>%
    left_join(df_species_predator,
              by="Predator_Species")
  
  df_ind_PPMR <- left_join(df_ind_PPMR_prelim, df_size_classes,
                           by="Predator_Size_Class")
  
  df_ind_PPMR <- df_ind_PPMR %>%
    select(Predator, Predator_Size, Predator_Abundance)
  
  df_ind_PPMR_plot <- left_join(df, df_ind_PPMR)
  
  df_final <- df_ind_PPMR_plot %>%
    mutate(per_capita_diet_N = ((Prey_Abundance/Predator_Abundance)/Prey_Size))
  
  df_final_clean <- df_final[Reduce(`&`, lapply(df_final, function(x) !is.na(x)  & is.finite(x))),]
  
  # # reorder factors
  # df$Predator <- factor(df$Predator, 
  #                       levels = c("Zooplankton", "Fish", "Inactive Cephs", "Active Cephs"))
  # 
  # df$Prey <- factor(df$Prey, 
  #                   levels = c("Phyto","Zooplankton", "Fish", "Inactive Cephs", "Active Cephs"))
  # 
  # unique_sizes <- sort(unique(df$Prey_Size))
  # df_sizes <- tibble(
  #   Prey_Size = unique_sizes, 
  #   Prey_size_class = 1:length(unique_sizes)
  # )
  # 
  # df <- left_join(df, df_sizes, by = "Prey_Size") %>%
  #   arrange(Predator, Prey, Predator_Size, Prey_Size)
  # 
  # df_sizes <- tibble(
  #   Predator_Size = unique_sizes, 
  #   Predator_size_class = 1:length(unique_sizes)
  # )
  # 
  # df <- left_join(df, df_sizes, by = "Predator_Size") %>%
  #   arrange(Predator, Prey, Predator_Size, Prey_Size)
  # 
  # # rm(df_d, df_pd)
  # 
  # df_Pred_Diet_N_sum <- df %>%
  #   group_by(Predator, Predator_Size, Prey_Size) %>%
  #   summarise(Total_Prey_Abundance = sum(Prey_Abundance)) %>%
  #   filter(Total_Prey_Abundance > 0)
  # 
  # # reorder factors
  # df$Predator <- factor(df$Predator, 
  #                       levels = c("Zooplankton", "Fish", "Inactive Cephs", "Active Cephs"))
  # 
  # df$Prey <- factor(df$Prey, 
  #                   levels = c("Phyto", "Zooplankton", "Fish", "Inactive Cephs", "Active Cephs"))
  
  
  # create a data frame for plotting
  df_plot_comb <- df_final_clean %>%
    mutate(PySzPyAb = Prey_Size*per_capita_diet_N) %>%  # total size
    group_by(Predator, Predator_Size) %>% # groups of prey distributions
    summarise(
      sum_prey_abundance = sum(per_capita_diet_N), # total prey numbers
      sum_PySzPyAb       = sum(PySzPyAb), # total size
      mean_prey_size     = sum_PySzPyAb / sum_prey_abundance # mean size
    )
  
  # data for dashed line where expected prey size is 10% of predator size
  # df_ref <- tibble(
  #   Predator_Size = c(min(df_Pred_Diet_N_sum$Predator_Size), max(df_Pred_Diet_N_sum$Predator_Size))
  # )
  # df_ref$Expected_Prey_Size_PPMR100000 = 0.00001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR10000 = 0.0001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR1000 = 0.001*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR100 = 0.01*df_ref$Predator_Size
  # df_ref$Expected_Prey_Size_PPMR10 = 0.1*df_ref$Predator_Size


  # ggplot() +
  #   geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR10),
  #             linetype = "solid") +
  #   geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR100),
  #             linetype = "solid") +
  #   geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR1000),
  #             linetype = "longdash") +
  #   geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR10000),
  #             linetype = "dashed") +
  #   geom_line(data = df_ref, aes(x = Predator_Size, y = Expected_Prey_Size_PPMR100000),
  #             linetype = "dotted") +
  #   geom_line(data = df_plot_comb,
  #             aes(x = Predator_Size, y = mean_prey_size, color = Predator), size = 1) +
  #   scale_x_log10() +
  #   scale_y_log10() +
  #   # facet_wrap( ~ Predator) +
  #   labs(x = "Predator size", y = "Mean prey size") +
  #   theme_bw()
  
  
  return(list(df_plot_comb, df_frac, df_ceph_prey_comb))
  
}

```




