---
title: "Preparing temperature forcing data for FishMIP projections"
author: "Kieran Murphy"
date:  "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
editor_options: 
  chunk_output_type: inline
---

Prydz Bay model domain 1,433,028 km2

From km2 to m2 1433028 * 1e6 = 1.433028e+12

Check the area for the model domain that gfdl ISIMIP data has been extracted for Prydz Bay

```{r}
# Load surface temperature data
df_gfdl_tos <- read.csv("FishMIP_Temperature_Forcing/gfdl-mom6-cobalt2_obsclim_tos_15arcmin_prydz-bay_monthly_1961_2010.csv") 

head(df_gfdl_tos)
```


```{r}
GFDL_tos <- df_gfdl_tos %>%
  select(!c(lat,lon,area_m2)) %>% # remove lat, lon and area_m2
  melt() %>% # surface temperature of each area for all grid cells
  group_by(variable) %>% # group by month
  rename(date = variable) %>%  # rename variable to something meaningful
  summarise(tos = mean(value)) # mean temperature across all grid cells in model region for each month


glimpse(GFDL_tos)
head(GFDL_tos)
```


Save temperature file

```{r}
# write.csv(GFDL_tos, "FishMIP_Temperature_Forcing/GFDL_Prydz_Bay_tos_mean.csv")
```





