---
title: "Explore background spectrum interaction"
output: html_notebook
---


```{r}
library(mizerExperimental)
library(therMizer)
library(tidyverse)
```



```{r}
model <- readRDS("ISIMIP3a_1961_2010_fishing.rds")
```


```{r}
p_therPerform <- therMizer::plotTherPerformance(model@params) 
# therMizer::plotTherScalar(model@params)

# ggsave("plots/Thermal_Performance_low_res.tiff", plot = p_therPerform, units="cm", width=24, height=14, dpi =150)

```


```{r}
p_B_Obs_vs_Mod <- plotBiomassObservedVsModel(model) +
  theme_classic() +
  theme(
    axis.title = element_text(size = 14),
    axis.text= element_text(size = 14),
    legend.position = "none"
  )
  

p_spectra <- plotSpectra(model) +
  theme_classic() +
  theme(
    axis.title = element_text(size = 14),
    axis.text= element_text(size = 14)
  )

# ggsave("plots/Biomass_Obs_vs_Mod.tiff", plot = p_B_Obs_vs_Mod, units="cm", width=16, height=14, dpi =300)
# ggsave("plots/Spectra.tiff", plot = p_spectra, units="cm", width=18, height=12, dpi =300)

# ggsave("plots/Biomass_Obs_vs_Mod_low_res.tiff", plot = p_B_Obs_vs_Mod, units="cm", width=16, height=14, dpi =150)
# ggsave("plots/Spectra_low_res.tiff", plot = p_spectra, units="cm", width=18, height=12, dpi =150)

# plotYieldObservedVsModel(model)
```


```{r}
model@params@species_params
tuneParams(model@params)
```


```{r}
plotSpectra(model, power = 1)
plot(model)
```


```{r}
p_growth <- plotGrowthCurves(model, species_panel = T) +
  theme_classic()

# ggsave("plots/Growth_Curves.tiff", plot = p_growth, units="cm", width=30, height=16, dpi =300)
ggsave("plots/Growth_Curves_low_res.tiff", plot = p_growth, units="cm", width=30, height=16, dpi =150)

```


```{r}
params <- model@params
```



```{r}
params@species_params$interaction_resource
```

```{r}
# params@species_params$interaction_resource <- 0.7

params@species_params$interaction_resource <- c(1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                1,
                                                0.5,
                                                0.5,
                                                0.5,
                                                0.5,
                                                0.3,
                                                0.3,
                                                0.3)
```


```{r}
params <- steady(params, preserve = c("erepro"))

params@species_params$erepro
```

```{r}
params <- params %>% matchBiomasses() %>% steady(t_max = 200, preserve = c("erepro")) %>% 
  matchBiomasses() %>% steady(t_max = 200, preserve = c("erepro")) %>% 
  matchBiomasses() %>% steady(t_max = 200, preserve = c("erepro")) %>% 
  matchBiomasses() %>% steady(t_max = 200, preserve = c("erepro")) %>% 
  matchBiomasses() %>% steady(t_max = 200, preserve = c("erepro"))
```



```{r}
params <- tuneParams(params)
```


```{r}
effort_array <- readRDS("effort_array_therMizer.rds")
```


```{r}
params_no_effort <- params 

params_no_effort@initial_effort <- 0
```

```{r}
params_effort <- params 

params_effort@initial_effort <- effort_array[1,]
```


# Using steady-state from reference period (2010-2019)
```{r}
# params_steady_F_init1961 <- projectToSteady(params, t_max = 1000, tol = 0.00001, effort = effort_array[1,],return_sim = T)
# params_steady_noF <- projectToSteady(params, t_max = 2000, tol = 0.00002, effort = 0, return_sim = T) # There is still a trend, need to run steady for longer
params_steady_F_init1961 <- steady(params_effort, t_max = 1000, tol = 0.00001, return_sim = T)
params_steady_noF <- steady(params_no_effort, t_max = 4000, tol = 0.0001, return_sim = T) # There is still a trend, need to run steady for longer


```

```{r}
plotBiomass(params_steady_F_init1961)
# plotBiomassRelative(params_steady_F_init1961)
```



```{r}
params_steady_noF@params@species_params$erepro
```

```{r}
params_steady_noF_erepro_preserved <- steady(params_no_effort, t_max = 1000, tol = 0.0001, return_sim = T, preserve = c("erepro")) # There is still a trend, need to run steady for longer
```
```{r}
plotBiomass(params_steady_noF_erepro_preserved)
plotBiomassRelative(params_steady_noF)
```


```{r}
plotBiomass(params_steady_noF)
plotBiomassRelative(params_steady_noF)
```


Run simulations:
```{r}

# And do a simulation using the steady parameters
projection_steady_F <- mizer::project(params_steady_F_init1961, t_max = 50, effort = effort_array)
projection_steady_noF <- mizer::project(params_steady_noF, t_start = 1961, t_max = 49,  effort = 0)
# projection_steady_F_init1961 <- mizer::project(params_steady_F_init1961, t_max = 50, effort = effort_array)

# projection_steady_validate <- mizer::project(params_steady_validate, t_max = 50,  effort = 0.2)

# Test to see how things look
plot(projection_steady_F)
plot(projection_steady_noF)
# plot(projection_steady_F_init1961)
# plot(projection_steady_validate)

plotYield(projection_steady_F)
# plotYield(projection_steady_F_init1961)

plotlyBiomass(projection_steady_F)
plotlyBiomass(projection_steady_noF)
# plotlyBiomass(projection_steady_F_init1961)

plotlyBiomassRelative(projection_steady_F)
plotlyBiomassRelative(projection_steady_noF)
# plotlyBiomassRelative(projection_steady_F_init1961)



saveRDS(projection_steady_F, "ISIMIP3a_1961_2010_fishing_v2.rds")
saveRDS(projection_steady_noF, "ISIMIP3a_1961_2010_no_fishing_v2.rds")

```

Proportion of diet observed vs proprtion modelled.

```{r}
plotDiet(projection_steady_F@params)
```

What story are we trying to target.
Conservtion and whale recovery is a better and
Fishing 

Mesopelagics

```{r}

```


```{r}
# projection_steady_F <- readRDS("ISIMIP3a_1961_2010_fishing.rds")
# projection_steady_noF <- readRDS("ISIMIP3a_1961_2010_no_fishing.rds")


p_B_Fish <- plotBiomass(projection_steady_F) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  )

p_B_no_Fish <- plotBiomass(projection_steady_noF) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  )

p_rel_B_Fish <- plotBiomassRelative(projection_steady_F) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  )

p_rel_B_no_Fish <- plotBiomassRelative(projection_steady_noF) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  )

p_B_Fish
p_B_no_Fish
p_rel_B_Fish
p_rel_B_no_Fish

ggsave("plots/Biomass_Fishing_low_Res.tiff", plot = p_B_Fish, units="cm", width=16, height=12, dpi =150)
ggsave("plots/Biomass_no_Fishing_low_Res.tiff", plot = p_B_no_Fish, units="cm", width=16, height=12, dpi =150)
ggsave("plots/Rel_Biomass_Fishing_low_Res.tiff", plot = p_rel_B_Fish, units="cm", width=16, height=12, dpi =150)
ggsave("plots/Rel_Biomass_no_Fishing_low_Res.tiff", plot = p_rel_B_no_Fish, units="cm", width=16, height=12, dpi =150)

```


```{r}
p_growth <- plotGrowthCurves(projection_steady_noF, species_panel = T) +
  theme_classic()

ggsave("plots/Growth_Curves.tiff", plot = p_growth, units="cm", width=30, height=16, dpi =300)
```




