###############################################################################
# FM02_species.R -- per-functional-group biomass (bsp) and catch (csp) density,
#                   on the phase-104 (q10) ensemble.
#
# Run:  Rscript run_p104q10.R R/fishmip_isimip3a/FM02_species.R
#
# Variables (g m-2, ensemble median / q05 / q25 / q75 / q95 over 203 members):
#
#   histsoc/bsp   per-group biomass density, fished arm
#   histsoc/csp   per-group catch density,   fished arm
#   nat/bsp       per-group biomass density, unfished arm
#
# All 19 groups appear in every file. The ten groups with catchability 0 carry
# csp = 0; that is a real zero, not a missing value.
#
# `bsp` and `csp` are NOT protocol variable names -- the ISIMIP3a vocabulary has
# no per-group biomass or catch variable. They are carried over from the
# previous submission, where they were requested as supporting detail, and are
# filed the same way.
#
# WHAT CHANGED FROM THE PREVIOUS BUILD
# ------------------------------------
# `FishMIP_ISIMIP3a_submission/extract_fishmip_outputs_species.R:50-52` took a
# fast path through three pre-computed summary CSVs from the retired
# 2,111-member ensemble. Those CSVs are not regenerated by anything in the
# current pipeline, so the old bsp/csp could not track the ensemble. This build
# goes to the member simulations directly.
#
# getBiomass() with its default use_cutoff = FALSE integrates the full size
# range, matching the tcb rule in FM01. 105_export_member_sims.R:415-449 already
# verified getBiomass() against the manuscript pipeline's hand-computed
# rowSums(sweep(n, 2, w*dw, "*")) to < 1e-10; FM06 re-checks the tie.
###############################################################################

source("R/fishmip_isimip3a/FM00_common.R")

src <- fm_member_source()
message("member source: ", src$kind, " | ", length(src$members), " members")

SPECIES <- NULL
TIMES   <- NULL

message("extracting per-species biomass and catch...")
Z <- fm_iterate(function(si, exploited, unexploited) {
  if (is.null(SPECIES)) {
    SPECIES <<- dimnames(exploited@n)[[2]]
    TIMES   <<- as.numeric(dimnames(exploited@n)$time)
  }
  bf <- getBiomass(exploited)      # time x species, grams over the domain
  bc <- getBiomass(unexploited)
  yf <- getYield(exploited)        # time x species, grams per year
  yc <- getYield(unexploited)
  stopifnot(identical(colnames(bf), SPECIES), identical(colnames(yf), SPECIES),
            identical(colnames(bc), SPECIES))
  list(bsp_histsoc = unname(bf) / MODEL_DOMAIN_AREA,
       bsp_nat     = unname(bc) / MODEL_DOMAIN_AREA,
       csp_histsoc = unname(yf) / MODEL_DOMAIN_AREA,
       csp_nat     = unname(yc) / MODEL_DOMAIN_AREA)
}, src = src)

nT <- length(TIMES); nM <- length(Z); nS <- length(SPECIES)
message(sprintf("extracted %d members x %d years x %d groups", nM, nT, nS))

stack_sp <- function(field) {
  a <- array(NA_real_, dim = c(nM, nT, nS),
             dimnames = list(member = names(Z), time = as.character(TIMES),
                             species = SPECIES))
  for (i in seq_len(nM)) a[i, , ] <- Z[[i]][[field]]
  a
}

RAW <- list(bsp_histsoc = stack_sp("bsp_histsoc"),
            bsp_nat     = stack_sp("bsp_nat"),
            csp_histsoc = stack_sp("csp_histsoc"),
            csp_nat     = stack_sp("csp_nat"))

## ---------------------------------------------------------------------------
## Assertions
## ---------------------------------------------------------------------------

if (max(abs(RAW$csp_nat)) != 0)
  stop("nat arm has non-zero per-species catch -- the unexploited simulations ",
       "are not unfished", call. = FALSE)
message("check: nat arm catch is identically zero -- ok")

fished <- SPECIES[apply(RAW$csp_histsoc, 3, max) > 0]
message("check: groups with non-zero modelled catch (", length(fished), "): ",
        paste(fished, collapse = ", "))
if (length(fished) != 9L)
  stop("expected 9 harvested groups, found ", length(fished), call. = FALSE)

if (min(RAW$bsp_histsoc) < 0 || min(RAW$bsp_nat) < 0)
  stop("negative biomass density", call. = FALSE)

## ---------------------------------------------------------------------------
## Ensemble statistics and CSVs
## ---------------------------------------------------------------------------

STATS <- lapply(RAW, ens_stats)

message("writing CSVs...")
fm_write_csv(stats_to_long_df(STATS$bsp_histsoc, TIMES, "species", SPECIES),
             FM_DIR_SPECIES, "histsoc", "bsp")
fm_write_csv(stats_to_long_df(STATS$csp_histsoc, TIMES, "species", SPECIES),
             FM_DIR_SPECIES, "histsoc", "csp")
fm_write_csv(stats_to_long_df(STATS$bsp_nat, TIMES, "species", SPECIES),
             FM_DIR_SPECIES, "nat", "bsp")

fm_dir(FM_WORK)
saveRDS(list(raw = RAW, stats = STATS, times = TIMES, species = SPECIES,
             fished = fished, members = as.integer(names(Z)),
             provenance = fm_provenance()),
        file.path(FM_WORK, "FM02_species.rds"))
message("  wrote ", file.path(FM_WORK, "FM02_species.rds"))

## ---------------------------------------------------------------------------
## Summary
## ---------------------------------------------------------------------------

cat("\n--- FM02 summary: ensemble-median biomass density (g m-2) ---\n")
cat(sprintf("%-26s %12s %12s %12s\n", "group", "1841 fished", "2010 fished", "2010 unfished"))
for (i in seq_len(nS))
  cat(sprintf("%-26s %12.4e %12.4e %12.4e\n", SPECIES[i],
              STATS$bsp_histsoc[1, i, "median"],
              STATS$bsp_histsoc[nT, i, "median"],
              STATS$bsp_nat[nT, i, "median"]))
cat("\nFM02 done.\n")
